### ISSUE TITLE
MultiQC does not recognize raw data (txt) from FastQC when in a collection

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#114]
**Problem:** The select menu does not find the FastQC collection input. However, it will find other ~collections~ individual dataset with the txt datatype. Both tool versions impacted and was not a problem before 18.05 pre-release afaik.

**Test history:** https://usegalaxy.org/u/jen/h/test-history-trimmomatic-trim-galore

**dataset 46 should be in the select list:**

<img width="999" alt="screen shot 2018-05-07 at 11 32 34 am" src="https://user-images.githubusercontent.com/8999735/39718723-01f0a27a-51ec-11e8-87fc-88301b45c918.png">

**tool form with other txt collection data in the history:** Drilling down into dataset 46 shows that the correct datatype is assigned.

<img width="999" alt="screen shot 2018-05-07 at 11 37 08 am" src="https://user-images.githubusercontent.com/8999735/39718724-020c5f1a-51ec-11e8-9d6b-a651e886e02f.png">
<img width="1001" alt="screen shot 2018-05-07 at 11 38 05 am" src="https://user-images.githubusercontent.com/8999735/39718725-022aeb7e-51ec-11e8-9a5f-e4f9777452dd.png">

**Comment by jennaj** [comment]
Retesting

**Comment by jennaj** [comment]
Still a problem with retest. Change back tags when fixed please and I'll test again

**Comment by martenson** [comment]
You made it a list of pairs (hid 46 on first picture) instead of a list. I think multiqc has no understanding of a list of pairs.

**Comment by blankenberg** [comment]
Which seems like a collection-in-tool framework problem, because you'll want to run a set of paired end datasets through fastQC and then through multiQC.

from multiqc:
```
                        <param name="input" type="data" format="txt" multiple="true" label="FastQC output">
                            <validator type="expression" message="MultiQC does not accept the HTML report generated by FastQC, only the Raw Data">value is not None and value.extension != "html"</validator>
                        </param>
```
it should accept multiple datasets, which I'd claim that a list:paired contains. Of course, from a framework level, its a bit ambiguous on how to handle this, e.g. batch for each sub-list/pair separately, or one tool run for all data -- probably should have multiple runtime-configurable options. 

fastQC works because it doesn't have `multiple="true" ` and it allows access to *batch* mode. 

Current work around is to flatten the collection manually into a list with collection operations, but this shouldn't really be necessary.

**Comment by jennaj** [comment]
Also reported here: https://github.com/galaxyproject/galaxy/issues/5875

**Comment by natefoo** [comment]
Looks like it's fixed in galaxyproject/galaxy#6255, it just needs to be backported to 18.05. Test was updated yesterday so we should be able to test there.

**Comment by mvdbeek** [comment]
So with that fix it's going to map over list:pairs if you have list of pairs, meaning you get one multiqc report per pair. 
Most likely you still need to unpack your list of pairs in most circumstances. This is because fastqc, the software (not the wrapper), is not paired-end aware. A paired-end aware QC tool would take in a pair and produce a single dataset.

**Comment by natefoo** [comment]
Assuming I did this right, it still doesn't see this collection: https://test.galaxyproject.org/u/nate/h/multiqc-input-test

**Comment by natefoo** [comment]
@mvdbeek Hrm, should the collection be selectable as an input now though?

**Comment by mvdbeek** [comment]
Yes, did you rebuild the client ?

**Comment by martenson** [comment]
@mvdbeek the client builds on-deploy for Test, it should be up to date

**Comment by mvdbeek** [comment]
The input datasets are deleted for me, so that may be an issue:
![screen shot 2018-06-05 at 16 29 26](https://user-images.githubusercontent.com/6804901/40982502-ae8f35de-68dd-11e8-8d8b-b83965c744d3.png)

**Comment by martenson** [comment]
they are not deleted for me, both before and after import... 😭

![screenshot 2018-06-05 10 31 25](https://user-images.githubusercontent.com/1814954/40982606-a39088a4-68ab-11e8-88fc-10a5a6e57261.png)
![screenshot 2018-06-05 10 31 06](https://user-images.githubusercontent.com/1814954/40982607-a3acf0a2-68ab-11e8-9d75-064473881b19.png)

**Comment by mvdbeek** [comment]
It just switched for me as well.

**Comment by mvdbeek** [comment]
there were some more related fixes, though they should all be in dev

**Comment by martenson** [comment]
Test is on https://github.com/galaxyproject/galaxy/commit/6911153c307ba25525df7c165b4f10b4260964ac

**Comment by mvdbeek** [comment]
Also there is a boolean parameter at the bottom that is being swallowed:
![screen shot 2018-06-05 at 16 49 31](https://user-images.githubusercontent.com/6804901/40983731-8b8d3dd0-68e0-11e8-971d-cced191ed5a1.png)

**Comment by jennaj** [comment]
Just re-tested at test.galaxyproject.org, still a problem, might be expected.

Test history: https://test.galaxyproject.org:/u/jenjackson/h/test-history-multiqc-at-testgalaxyproject 

Tested all three collection types, none have the .txt FastQC recognized by the tool yet.

<img width="1205" alt="screen shot 2018-06-05 at 11 17 35 am" src="https://user-images.githubusercontent.com/8999735/40994872-551d3fd0-68b2-11e8-8945-71fcd0e88a04.png">

**Comment by jennaj** [comment]
Added tags to the tests so others can better understand what those are.

I tried to drag and drop out of a collection. One worked Ok (forward), the other shows up wierd in the select list. Is that a known or just something buggy on Test? I'll see if can reproduce on `org`.

<img width="989" alt="screen shot 2018-06-05 at 11 32 24 am" src="https://user-images.githubusercontent.com/8999735/40995632-7667de5a-68b4-11e8-9c28-9961d6eb8cfb.png">

**Comment by jennaj** [comment]
At Main/`org`, same issues with dropped datasets, actually worse, all show up in the select with "Dropped: XXXXXX" not the dataset name with (hidden). Does this need a different ticket or is it a known? @jmchilton 

test history, dataset 48 is what I tested with dragging the collection files over into MultiQC

<img width="489" alt="screen shot 2018-06-05 at 11 41 40 am" src="https://user-images.githubusercontent.com/8999735/40996034-afdec24c-68b5-11e8-9e59-572f9b7ff323.png">

**Comment by jennaj** [comment]
Related, should probably be open again and not closed. https://github.com/galaxyproject/tools-iuc/issues/1658

**Comment by martenson** [comment]
simple list of raw data from fastqc works fine for me with multiqc, https://usegalaxy.org/u/martenson/h/unnamed-history-2

**Comment by jennaj** [comment]
Interesting, dataset 32 is basically the same content and doesn't work. Yours was a new list collection of merged txt output, might was produced from a list of fastq datasets that was run through Fastqc as collection list input. 

Not sure what the difference is under the hood, but is a really good test/comparison. Maybe will help figure out what is going wrong.

**Comment by mvdbeek** [comment]
Can we create one issue per issue ? I see different servers with different galaxy versions with different inputs dragged or not dragged. This is very confusing.
That regular lists can't be selected with multidata inputs (as in the case for multiqc) on dev should be fixed by https://github.com/galaxyproject/galaxy/pull/6300. 

Selecting pairs or list of pairs in a multidata input can be made possible, but is probably not the right thing to do as it wouldn't do what you would like it to do. The correct thing is to use a QC tool that is paired-end aware and outputs a single report per fastq pair or to unzip the collection and use a regular list.
