### ISSUE TITLE
Sort v 1.1.0 fails at usegalaxy.org 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#210]
Isolated to usegalaxy.org. Version 1.1.0 works fine at usegalaxy.eu and in a 19.01 local (default version included in the release).

**Workaround for end-users:** Use version 1.1.1 instead until fixed. Search the tool panel with the keyword "sort" and use the version under the tool group "Text Manipulation".

Test histories: 
 - https://usegalaxy.org:/u/jen/h/test-textmani-sort 
 - https://usegalaxy.eu:/u/jenj/h/test-textmani-sort 

Error from version 1.1.0 at usegalaxy.org:

```
Fatal error: Exit code 1 ()
Error running sorter.py
Command '(grep '^#' /galaxy-repl/main/files/030/997/dataset_30997139.dat) >> /galaxy-repl/main/files/030/997/dataset_30997144.dat' returned non-zero exit status 1
```

ping @natefoo @davebx

**Comment by jennaj** [comment]
Rats, this is included in the galaxy 101 tutorial, so that probably bumps it up in priority. Looks like it starting failing mid-day today (4/17/19).

**Comment by jmchilton** [comment]
We reviewed this and I think the dependencies are probably just not installed or need to be installed on main. I think the fix would be to open an CVMFS transaction and install or re-install the conda dependencies from the admin app (usegalaxy.org/admin -> Manage Dependencies -> Tool Centric View -> Click Sort and install). Should create _conda/envs/mulled-v1-8ff473de1e395cfc8480749588a813689f1dfdd8f4af52c3c77b067d14da5042.

**Comment by mvdbeek** [comment]
There are 2+ different tools, Bjoern's tool has no `sorter.py` file, this is the tool that ships with Galaxy that is failing in the opening post. This was broken for files with a header line that includes a `#` with https://github.com/galaxyproject/galaxy/pull/7679 and fixed with https://github.com/galaxyproject/galaxy/pull/7679

So the tool that was broken was https://usegalaxy.org/tool_runner?tool_id=sort1. I just reran this with and without header line and it ran successfully.

**Comment by jmchilton** [comment]
I assumed it was a dependency problem because 100% of tool executions for this tool were failing on usegalaxy.org... okay thanks for the clarification.

**Comment by mvdbeek** [comment]
No problem, it just sounded eerily familiar :/

**Comment by jennaj** [comment]
Stray open ticket for issue resolved already, closing out.
