### ISSUE TITLE
Tophat not working

### ISSUE THREAD

**Issue by rpotens007** [galaxyproject/usegalaxy-playbook#260]
Tophat on Galaxy is not working.

**Comment by jennaj** [comment]
Yes, there were some job delays/errors based on server-side issues when you reported the issue. Those are not resolved. Related Galaxy Help post: https://help.galaxyproject.org/t/bowtie2-not-working/2142/26?u=jennaj

_Please be warned_: `Tophat` is a deprecated tool. Meaning, it is no longer maintained and may produce errors or unexpected results (not always easy to find!). The replacement mapping tool is `HISAT2`. Or, in some use cases, `RNA-STAR`. 

Tutorials that use upgraded tools/methods are hosted by the [Galaxy Training Network (GTN)](https://galaxyproject.org/teach/gtn/). Start with those in the group "Transcriptomics" for RNAseq analysis.

These FAQ may also be helpful: 

* [My job ended with an error. What can I do?](
* [Extended Help for Differential Expression Analysis Tools](https://galaxyproject.org/support/diff-expression/)

Using Galaxy Help https://help.galaxyproject.org to report problems is the preferred method of reporting tool problems. You may find that the topic is already opened/answered when the problem is server-side _plus_ when it is usage-based.
