### ISSUE TITLE
tool error

### ISSUE THREAD

**Issue by sharmavikas44** [galaxyproject/usegalaxy-playbook#316]
AN issue "The tool was executed with one or more duplicate input datasets. This frequently results in tool errors due to problematic input choices." occurred while using trinity. How can it be resolved?

**Comment by jennaj** [comment]
Hi @sharmavikas44 

Questions about tool usage or errors are best asked at the Galaxy Help forum https://help.galaxyproject.org/ (instead of Github).

I noticed this as well at the usegalaxy.eu server when using Trinity and have an answer that may or may not apply to your use-case. If you are working at usegalaxy.org,  the answer will be different and is probably already what we know about but that can also be confirmed. 

Please include the following in your post at Galaxy Help. I'll edit the topic post title if needed (a post with the title "tool error" is not descriptive enough). 

1. The URL of the public Galaxy server you are working at. If you are not working at a public Galaxy site, please describe (local, cloud, gvl, other -- along with the version of Galaxy installed or a link to where/when Galaxy was sourced).

2. Full name of the tool including the version. This is located at the very top of each tool form.

3. How the tool is being used. A short description of the inputs (from a tutorial? include a link to the tutorial please) and a screenshot of the job's parameters. Find this information by expanding the error dataset, click on the "i" (View Details) icon, and screenshot the page displayed in the center panel of Galaxy. Make sure all three top sections are included (Ok if it requires two screenshots to capture it all). If you want to mask lines out of your screenshot associated with your specific data, that is Ok.

4. Please include a link to this Github issue ticket (the browser URL), so we can link the two together.

----
**How-to mask out content in screenshots**: edit the screenshot to mask lines with data identification content (the areas with a strike-through below)

> History Content API ID: | ~~bbd44e69cb8906b5a6de55ce19d96217 (61139399)~~
> Job API ID: | ~~bbd44e69cb8906b5136e95268a32d2a0 (31622019)~~
> History API ID: | ~~01beef5fe5d49dee (4635609)~~
> UUID: | ~~1d4d9593-d3df-4e7c-8439-053c32d000c1~~
> Full Path: | ~~/galaxy-repl/main/files/047/089/dataset_47089011.dat~~

**Any simple graphics editor can be used** (for example: Preview on macOS)

<img width="1184" alt="Screen Shot 2020-12-01 at 9 19 32 AM" src="https://user-images.githubusercontent.com/8999735/100774058-872efc80-33b6-11eb-9d08-5f2d1836eab7.png">

**The goal is to produce a screen like this one**: can be more than one screenshot if the content is too long to fit into one

<img width="660" alt="job-details-with-masked-data-identifiers" src="https://user-images.githubusercontent.com/8999735/100776090-f3aafb00-33b8-11eb-8d66-c1ecf016f27e.png">

----

That should be enough to help you, but if not we can follow up at Galaxy Help, including moving to a direct message there to keep the details private. We may ask for a bug report as well -- but let's get some more details first.

Thanks for your help. A topic with your exact question has not been posted yet at Galaxy Help, and the public Q&A will help both you and others with troubleshooting this type of error (in general) plus we can diagnose which solution is a fit for your specific error.
