### ISSUE TITLE
Problem with Galaxy + repeat explorer 

### ISSUE THREAD

**Issue by CornilleAmandine** [galaxyproject/usegalaxy-playbook#339]
Hello

Does anyone could help me with a problem I have when trying to run repeat explorer on galaxy?

I use my fasta file, I can import it

I run it for a test using 11000 reads.

Repeat explorer worked well until I had these error messages 
[Galaxy5-[RepeatExplorer2_-_log_file].txt](https://github.com/galaxyproject/usegalaxy-playbook/files/6453440/Galaxy5-.RepeatExplorer2_-_log_file.txt)

Shutting down Rserv...Done
connection to Rserve refused, server is probably already down
STDERR CONTENT:
fatal: not a git repository (or any parent up to mount point /auto/brno11-elixir)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)./

I bet this is not link to repeat explorer but a Galaxy server issue? Right ?

thanks a lot in advance for your help!!
my best,
Amandine

**Comment by jennaj** [comment]
Hi -- Next time or if you are still having problems now, please ask questions or report problems at the Galaxy Help forum: https://help.galaxyproject.org/

1. Review the most recent Q&A -- there may already be a post with feedback/status 
2. Open a new topic if no one else has reported a problem yet
3. Be sure to note the URL of the public Galaxy server you are working at, or describe if the problem is some other place
4. Then share a bit about the problem you are having as "not working" can mean a few different things. Community moderators can help more when they have some basic information to start from. Screenshots, error messages, tool name/version -- the type of information found on the "Error report" when clicking on the "bug" icon is usually a good place to start. You can even send in a bug report and also note that you did so in your post. All help :)

FAQs: 
* https://training.galaxyproject.org/training-material/faqs/galaxy/#troubleshooting-errors
* https://training.galaxyproject.org/training-material/faqs/gtn/#what-information-should-i-include-when-reporting-a-problem
