### ISSUE TITLE
Trinity error

### ISSUE THREAD

**Issue by vietdungria** [galaxyproject/usegalaxy-playbook#342]
Trinity errors and couldn't work for the past few days,  can someone check it?

**Comment by jennaj** [comment]
Hi -- Next time, please ask questions or report problems at the Galaxy Help forum: https://help.galaxyproject.org/

1. Review the most recent Q&A -- there may already be a post with feedback/status 
2. Open a new topic if no one else has reported a problem yet
3. Be sure to note the URL of the public Galaxy server you are working at, or describe if the problem is some other place
4. Then share a bit about the problem you are having as "not working" can mean a few different things. Community moderators can help more when they have some basic information to start from. Screenshots, error messages, tool name/version -- the type of information found on the "Error report" when clicking on the "bug" icon is usually a good place to start. You can even send in a bug report and also note that you did so in your post. All help :)

FAQs: 
* https://training.galaxyproject.org/training-material/faqs/galaxy/#troubleshooting-errors
* https://training.galaxyproject.org/training-material/faqs/gtn/#what-information-should-i-include-when-reporting-a-problem
